# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
