# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_bookmark_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='short_name',
            field=models.CharField(default='dENR1LxZ', max_length=8),
        ),
    ]
